#!/usr/bin/env bash
# Write a Bash script that configures a server
sed -i "s/listen 8080 default_server;/listen 80 default_server;/" /etc/nginx/sites-enabled/default
sed -i "s/listen \[::\]:8080 default_server ipv4=on;/listen \[::\]:80 default_server;/" /etc/nginx/sites-enabled/default
sed -i "s/ ipv4=on//" /etc/nginx/sites-available/default
service nginx restart
